-- AlterTable
ALTER TABLE "Round" ALTER COLUMN "clientSeed" DROP NOT NULL,
ALTER COLUMN "combinedSeed" DROP NOT NULL,
ALTER COLUMN "pegMapHash" DROP NOT NULL,
ALTER COLUMN "rows" SET DEFAULT 12,
ALTER COLUMN "dropColumn" DROP NOT NULL,
ALTER COLUMN "binIndex" DROP NOT NULL,
ALTER COLUMN "payoutMultiplier" DROP NOT NULL,
ALTER COLUMN "betCents" DROP NOT NULL,
ALTER COLUMN "pathJson" DROP NOT NULL;
